### ISSUE TITLE
[Feature request] HugoMods module to integrate Apache Echarts for data visualisation

### ISSUE THREAD

**Issue by ezzle** [hugomods/echarts#4]
Hi

### Requested Feature
A HugoMods module to support the Echarts  interactive data visualization

**data definition options**

1. via data/*
2. as shortcode content

### What'is ECharts
An Open Source JavaScript feature rich Data Visualization Library.
`A Declarative Framework for Rapid Construction of Web-based Visualization`
https://echarts.apache.org/en/index.html

### Third party integration
**from [LoveIt](https://hugoloveit.com/)**
`The echarts shortcode supports data visualization in Hugo with [ECharts](https://echarts.apache.org/) library.`
https://hugoloveit.com/theme-documentation-echarts-shortcode/

Best regards,

Tshitshi

**Comment by ezzle** [comment]
Hi razon.
Thank you very much.
Testing ...

**Comment by ezzle** [comment]
Hi Razon,
The 3 options works fine.
Thank you very much.
The current testing just validate the 3 options are operational.
Later, more testing with real-life use cases and in combination with other hugomods modules.
Thank you for the excellent work and the extreme reactivity.

Best regards,

Tshitshi

**Comment by razonyang** [comment]
> Later, more testing with real-life use cases and in combination with other hugomods modules.

Yes please, I'm not sure if the API (code block and shortcode) covers all user cases.

Let me know if it works with real-life user cases, I will release the version after that, so that we won't break much things in the future.

**Comment by razonyang** [comment]
Closed as implemented, please open another issue if there is any problem.

**Comment by ezzle** [comment]
Thank you very much. Excellent job!

Best regards

Le jeu. 14 mars 2024 à 10:31, Razon Yang ***@***.***> a
écrit :
